baseURL: "bataragaradu.github.io/rbblog-forest-hugo/"
publishDir: "docs"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
