baseURL: "https://frosty-wiles-7881c0.netlify.app/"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  github: "#"
  linkedin: "#"
taxonomies:
  author: "Bataraga Radu"
